parameters:
#    msp_registration.example.class: MSP\RegistrationBundle\Example

services:
#    msp_registration.example:
#        class: %msp_registration.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
